name: rl_energy
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.6
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1o
  - pillow=9.0.1
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.27.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.3
  - tk=8.6.11
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - cftime==1.6.0
    - click==8.1.3
    - cloudpickle==2.0.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - gym==0.23.1
    - gym-notices==0.0.6
    - h5py==3.6.0
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - ipykernel==6.15.1
    - ipython==8.3.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.5.1
    - jupyter==1.0.0
    - jupyter-client==7.3.1
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - netcdf4==1.5.8
    - notebook==6.4.11
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.29
    - protobuf==4.21.0-rc-1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pvlib==0.9.1
    - pygments==2.12.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.3.0
    - qtpy==2.1.0
    - scipy==1.8.0
    - send2trash==1.8.0
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - siphon==0.9
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - terminado==0.15.0
    - tinycss2==1.1.1
    - tornado==6.1
    - traitlets==5.2.1.post0
    - wandb==0.12.16
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - zipp==3.8.0