# Configuration params for discrete A2C
train:
  agent:
    num_disc_act: 40
    actor_lr: 0.00245
    critic_lr: 0.001
    actor_nn: 128
    critic_nn: 128
    gamma: 1.0
    disable_logging: True
    enable_gpu: True
    extended_observation: False 
  env:
    batch_size: 32
    rollout_steps: 24
    training_steps: 2000
    central_agent: False
    disable_noise: True
    encoding: True
    peak_grid_gen: 1
    grid_sell_rate: 0.25
    min_temp: 29
    max_temp: 31
    houses:
      train:
        house_1:
          profile:
            type: family
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_2:
          profile:
            type: business
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_3:
          profile:
            type: teenagers
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_4:
          profile:
            type: family
            peak_load: 0.5
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.0
        house_5:
          profile:
            type: business
            peak_load: 0.3
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_6:
          profile:
            type: teenagers
            peak_load: 0.2
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.6
      eval:
        house_1:
          profile:
            type: family
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.5
        house_2:
          profile:
            type: business
            peak_load: 0.8
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_3:
          profile:
            type: teenagers
            peak_load: 0.5
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
        house_4:
          profile:
            type: family
            peak_load: 0.2
          battery:
            random_soc_0: False
            capacity: 0.5
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_5:
          profile:
            type: business
            peak_load: 0.3
          battery:
            random_soc_0: False
            capacity: 0.9
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.3
        house_6:
          profile:
            type: teenagers
            peak_load: 0.2
          battery:
            random_soc_0: False
            capacity: 0.9
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.6
      test:
        house_1:
          profile:
            type: family
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
        house_2:
          profile:
            type: business
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
        house_3:
          profile:
            type: teenagers
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
        house_4:
          profile:
            type: family
            peak_load: 0.2
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.7
        house_5:
          profile:
            type: business
            peak_load: 0.6
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_6:
          profile:
            type: teenagers
            peak_load: 0.4
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.7
        house_7:
          profile:
            type: family
            peak_load: 0.4
          battery:
            random_soc_0: False
            capacity: 0.8
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_8:
          profile:
            type: business
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 0.2
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_9:
          profile:
            type: teenagers
            peak_load: 0.1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_10:
          profile:
            type: family
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 0.2
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
# reward?
