# Configuration params for discrete A2C
train:
  agent:
    num_disc_act: 40
    actor_lr: 0.05245
    critic_lr: 0.001
    actor_nn: 128
    critic_nn: 128
    gamma: 1.0
    disable_logging: True
    enable_gpu: True
    extended_observation: False 
  env:
    batch_size: 32
    rollout_steps: 24
    training_steps: 700
    central_agent: False
    random_soc_0: False
    disable_noise: True
    encoding: True
    peak_pv_gen: 1
    peak_grid_gen: 1
    peak_load: 1
    grid_sell_rate: 0.25
    min_temp: 29
    max_temp: 31
    profile: Family
    solar: True
# reward?
