# Configuration params for discrete A2C
train:
  agent:
    num_disc_act: 40
    actor_lr: 0.004386
    critic_lr: 0.0002
    actor_nn: 64
    critic_nn: 512
    gamma: 1.0
    disable_logging: False
    enable_gpu: True
    extended_observation: False 
  env:
    batch_size: 32
    rollout_steps: 24
    training_steps: 10000
    switch_steps: 1000
    central_agent: False
    disable_noise: True
    encoding: True
    min_temp: 29
    max_temp: 31
    grid:
      profiles:
        profile_1:
          name: 'quiet evening'
          peak_gen: 1
          import_fraction: 0.25
          l1_fee: 0.01
          l1_alpha: 0.001
          l1_beta: 0.001
          nuclear_energy_rate: 0.6
          nuclear_price: 0.1
          nuclear_emission_factor: 0.1
          gas_price: 0.5
          gas_emission_factor: 0.9
          gas_profile: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.6, 1.0, 0.6, 0.3, 0.3, 0.3, 0.3, 0.6, 1.0, 0.6, 0.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        profile_2:
          name: 'quiet noon'
          peak_gen: 1
          import_fraction: 0.25
          l1_fee: 0.01
          l1_alpha: 0.0005
          l1_beta: 0.0003
          nuclear_energy_rate: 0.4
          nuclear_price: 0.1
          nuclear_emission_factor: 0.1
          gas_price: 0.5
          gas_emission_factor: 0.9
          gas_profile: [0.3, 0.3, 0.3, 0.3, 0.6, 0.7, 1.0, 1.0, 0.6, 0.5, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.5, 0.7, 1.0, 1.0, 1.0, 1.0, 0.7, 0.6]
        profile_3:
          name: 'active noon'
          peak_gen: 1
          import_fraction: 0.25
          l1_fee: 0.01
          l1_alpha: 0.0002
          l1_beta: 0.0004
          nuclear_energy_rate: 0.4
          nuclear_price: 0.1
          nuclear_emission_factor: 0.1
          gas_price: 0.5
          gas_emission_factor: 0.9
          gas_profile: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.5, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.5, 0.7, 1.0, 1.0, 1.0, 1.0, 0.7, 0.6]
        profile_4:
          name: 'nuclear'
          peak_gen: 1
          import_fraction: 0.35
          l1_fee: 0.01
          l1_alpha: 0.0004
          l1_beta: 0.0002
          nuclear_energy_rate: 1
          nuclear_price: 0.1
          nuclear_emission_factor: 0.1
          gas_price: 0.5
          gas_emission_factor: 0.9
          gas_profile: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        profile_5:
          name: 'gas'
          peak_gen: 1
          import_fraction: 0.15
          l1_fee: 0.01
          l1_alpha: 0.0008
          l1_beta: 0.0009
          nuclear_energy_rate: 0
          nuclear_price: 0.1
          nuclear_emission_factor: 0.1
          gas_price: 0.5
          gas_emission_factor: 0.9
          gas_profile: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        profile_6:
          name: 'gas mainly'
          peak_gen: 1
          import_fraction: 0.15
          l1_fee: 0.01
          l1_alpha: 0.0007
          l1_beta: 0.0002
          nuclear_energy_rate: 0.2
          nuclear_price: 0.1
          nuclear_emission_factor: 0.1
          gas_price: 0.5
          gas_emission_factor: 0.9
          gas_profile: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    houses:
      train:
        house_1:
          profile:
            type: family
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_2:
          profile:
            type: business
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_3:
          profile:
            type: teenagers
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_4:
          profile:
            type: family
            peak_load: 0.5
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.0
        house_5:
          profile:
            type: business
            peak_load: 0.3
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_6:
          profile:
            type: teenagers
            peak_load: 0.2
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.6
      eval:
        house_1:
          profile:
            type: family
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.5
        house_2:
          profile:
            type: business
            peak_load: 0.8
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_3:
          profile:
            type: teenagers
            peak_load: 0.5
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
        house_4:
          profile:
            type: family
            peak_load: 0.2
          battery:
            random_soc_0: False
            capacity: 0.5
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_5:
          profile:
            type: business
            peak_load: 0.3
          battery:
            random_soc_0: False
            capacity: 0.9
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.3
        house_6:
          profile:
            type: teenagers
            peak_load: 0.2
          battery:
            random_soc_0: False
            capacity: 0.9
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.6
      test:
        house_1:
          profile:
            type: family
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
        house_2:
          profile:
            type: business
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
        house_3:
          profile:
            type: teenagers
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.90
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
        house_4:
          profile:
            type: family
            peak_load: 0.2
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.7
        house_5:
          profile:
            type: business
            peak_load: 0.6
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_6:
          profile:
            type: teenagers
            peak_load: 0.4
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0.7
        house_7:
          profile:
            type: family
            peak_load: 0.4
          battery:
            random_soc_0: False
            capacity: 0.8
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_8:
          profile:
            type: business
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 0.2
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_9:
          profile:
            type: teenagers
            peak_load: 0.1
          battery:
            random_soc_0: False
            capacity: 1
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 1
        house_10:
          profile:
            type: family
            peak_load: 1
          battery:
            random_soc_0: False
            capacity: 0.2
            efficiency: 0.5
            soc_max: 0.9
            soc_min: 0.1
            p_charge_max: 0.8
            p_discharge_max: 0.8
            efficiency: 0.9
            sell_price: 0.0
            buy_price: 0.0
          pv:
            peak_pv_gen: 0
# reward?
