# Configuration params for discrite A2C
train:
  batch_size: 64
  training_steps: 500
  rollout_steps: 24
  num_disc_act: 20
  actor_lr: 0.0001
  critic_lr: 0.0001
  actor_nn: 256
  critic_nn: 256
  gamma: 0.90
  epsilon: 0.90
  random_soc_0: False
  disable_noise: True
  disable_logging: False
  enable_gpu: True
  central_agent: False
  encoding: False
  extended_observation: False 
# reward?
