# Configuration params for discrite A2C
train:
  batch_size: 32
  training_steps: 500
  rollout_steps: 24
  num_disc_act: 12
  actor_lr: 0.00008
  actor_nn: 256
  gamma: 0.90
  random_soc_0: False
  disable_noise: True
  disable_logging: True
  enable_gpu: True
  central_agent: False
  encoding: True
  extended_observation: False 
# reward?
