# Configuration params for Random and Zero agents 
train:
  agent:
    disable_logging: False
    enable_gpu: True
    extended_observation: False 
  env:
    batch_size: 1
    rollout_steps: 24
    training_steps: 2
    central_agent: False
    random_soc_0: False
    disable_noise: True
    encoding: True
    peak_pv_gen: 1
    peak_grid_gen: 1
    peak_load: 1
    grid_sell_rate: 0.25
    min_temp: 29
    max_temp: 31
    profile: Family
    solar: True
# reward?
